name: Doodle
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # at the end of each day
jobs:
  doodle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          ref: main
      - name: Run
        continue-on-error: true
        run: |
          ls -las
          # git config --global user.email "you@example.com"
          # git config --global user.name "Github Action"
          # pip3 install -r requirements.txt
          # python3 read.py
          # git add README.md
          # git commit -m "update"
          # git push
          echo "TESTVAR=$(cat README.md)" >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo "::set-output name=FILE::$(cat README.md)"
        id: fileaction
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Ciao Nasi!
            
            Ecco i turni:
            
            ${{ steps.fileaction.outputs.FILE }}

            ${{ env.TESTVAR }}
            
            $(cat README.md)
           
