name: monthly-check
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 28 * *' # ogni 28 del mese
jobs:
  doodle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Export turni
        run: |
          curl -X GET "${{ secrets.URL }}&monthly=true" > turni_mensili.txt
          export CHANGELOG="$(cat turni_mensili.txt)"
          echo "$CHANGELOG"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=FILE::$(echo "$CHANGELOG")"
        id: fileaction
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ steps.fileaction.outputs.FILE }}
